create database AI_hate;
use AI_hate;

CREATE TABLE ChatScreenshots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT NOT NULL,
    label VARCHAR(20)
);

INSERT INTO ChatScreenshots (content, label) VALUES
('hey, you are so stupid!', 'hate speech'),
('i hate you, go die!', 'hate speech'),
('you are ugly and worthless', 'hate speech'),
('stop being such a loser!', 'hate speech'),
('i can''t stand people like you', 'hate speech'),
('you should be ashamed of yourself', 'hate speech'),
('you''re such a disgrace to society', 'hate speech'),
('i hope you fail miserably', 'hate speech'),
('you don''t belong here', 'hate speech'),
('why are you even alive?', 'hate speech'),
('you''re a waste of space', 'hate speech'),
('i wish you were never born', 'hate speech'),
('you make me sick', 'hate speech'),
('nobody likes you', 'hate speech'),
('you deserve to be alone', 'hate speech'),
('you''re pathetic', 'hate speech'),
('i''m disgusted by you', 'hate speech'),
('you''re a worthless human being', 'hate speech'),
('i hope something terrible happens to you', 'hate speech'),
('you should just kill yourself', 'hate speech'),
('you''re so annoying', 'hate speech'),
('i don''t want to talk to you', 'hate speech'),
('you''re such a burden', 'hate speech'),
('you''re a failure', 'hate speech'),
('i wish you were never born', 'hate speech'),
('you''re a waste of space', 'hate speech'),
('you''re a disappointment', 'hate speech'),
('nobody cares about you', 'hate speech'),
('you''re a joke', 'hate speech'),
('tu bahut stupid hai', 'hate speech'),
('tum ghadhe ho', 'hate speech'),
('teri aukat nahi hai.', 'hate speech'),
('tumhari shakal dekhne layak nahi hai.', 'hate speech'),
('tu bilkul bewakoof hai.', 'hate speech'),
('tujh jaiso se mujhe nafrat hai.', 'hate speech'),
('badir', 'hate speech'),
('bakland', 'hate speech'),
('bhootnika', 'hate speech'),
('chinaal', 'hate speech'),
('chup', 'hate speech'),
('ghasti', 'hate speech'),
('chutiye', 'hate speech'),
('chutye', 'hate speech'),
('hijra', 'hate speech'),
('hinjda', 'hate speech'),
('jaanvar', 'hate speech'),
('kutta', 'hate speech'),
('khota', 'hate speech'),
('auladheen', 'hate speech'),
('jaat', 'hate speech'),
('najayaz', 'hate speech'),
('sala', 'hate speech'),
('saala', 'hate speech'),
('kutti', 'hate speech'),
('suwar', 'hate speech'),
('soover', 'hate speech'),
('tatti', 'hate speech'),
('potty', 'hate speech'),
('bahenchod', 'hate speech'),
('bahanchod', 'hate speech'),
('bahencho', 'hate speech'),
('bancho', 'hate speech'),
('bahenke', 'hate speech'),
('laude', 'hate speech'),
('takke', 'hate speech'),
('betichod', 'hate speech'),
('bhaichod', 'hate speech'),
('bhains', 'hate speech'),
('jhalla', 'hate speech'),
('jhant', 'hate speech'),
('nabaal', 'hate speech'),
('pissu', 'hate speech'),
('kutte', 'hate speech'),
('maadherchod', 'hate speech'),
('madarchod', 'hate speech'),
('padma', 'hate speech'),
('raand', 'hate speech'),
('jamai', 'hate speech'),
('randwa', 'hate speech'),
('randi', 'hate speech'),
('bachachod', 'hate speech'),
('bachichod', 'hate speech'),
('soower', 'hate speech'),
('bachchechod', 'hate speech'),
('ullu', 'hate speech'),
('pathe', 'hate speech'),
('banda', 'hate speech'),
('booblay', 'hate speech'),
('booby', 'hate speech'),
('buble', 'hate speech'),
('babla', 'hate speech'),
('bhonsriwala', 'hate speech'),
('bhonsdiwala', 'hate speech'),
('ched', 'hate speech'),
('chut', 'hate speech'),
('chod', 'hate speech'),
('chodu', 'hate speech'),
('chodra', 'hate speech'),
('choochi', 'hate speech'),
('chuchi', 'hate speech'),
('gaandu', 'hate speech'),
('gandu', 'hate speech'),
('gaand', 'hate speech'),
('lavda', 'hate speech'),
('lawda', 'hate speech'),
('lauda', 'hate speech'),
('lund', 'hate speech'),
('balchod', 'hate speech'),
('lavander', 'hate speech'),
('muth', 'hate speech'),
('maacho', 'hate speech'),
('mammey', 'hate speech'),
('tatte', 'hate speech'),
('toto', 'hate speech'),
('toota', 'hate speech'),
('backar', 'hate speech'),
('bhandwe', 'hate speech'),
('bhosadchod', 'hate speech'),
('bhosad', 'hate speech'),
('bumchod', 'hate speech'),
('bum', 'hate speech'),
('bur', 'hate speech'),
('chatani', 'hate speech'),
('cunt', 'hate speech'),
('cuntmama', 'hate speech'),
('chipkali', 'hate speech'),
('pasine', 'hate speech'),
('jhaat', 'hate speech'),
('chodela', 'hate speech'),
('bhagatchod', 'hate speech'),
('chhola', 'hate speech'),
('chudai', 'hate speech'),
('chudaikhana', 'hate speech'),
('chunni', 'hate speech'),
('choot', 'hate speech'),
('dhakkan', 'hate speech'),
('bhajiye', 'hate speech'),
('fateychu', 'hate speech'),
('gandnatije', 'hate speech'),
('lundtopi', 'hate speech'),
('kutha', 'hate speech'),
('harami', 'hate speech'),
('haramzada', 'hate speech'),
('kutti', 'hate speech'),
('kuttiya', 'hate speech'),
('kamine', 'hate speech'),
('kaminey', 'hate speech'),
('suar', 'hate speech'),
('blackie', 'hate speech'),
('nigger', 'hate speech'),
('half-breed', 'hate speech'),
('hillbilly', 'hate speech'),
('honky', 'hate speech'),
('injun', 'hate speech'),
('gyppo', 'hate speech'),
('kike', 'hate speech'),
('kraut', 'hate speech'),
('mic', 'hate speech'),
('pikey', 'hate speech'),
('spic', 'hate speech'),
('kaale', 'hate speech'),
('kaali', 'hate speech'),
('kalu', 'hate speech'),
('kalia', 'hate speech'),
('kaaliya', 'hate speech'),
('gore', 'hate speech'),
('gori', 'hate speech'),
('goriya', 'hate speech'),
('kaale saale', 'hate speech'),
('kala kaluta', 'hate speech'),
('gore chale', 'hate speech'),
('gori chamdi', 'hate speech'),
('kaale chakkar', 'hate speech'),
('kala kauva', 'hate speech'),
('gore gadhe', 'hate speech'),
('gori chamdi wale', 'hate speech'),
('faggot', 'hate speech'),
('dyke', 'hate speech'),
('homo', 'hate speech'),
('queer', 'hate speech'),
('pansy', 'hate speech'),
('sissy', 'hate speech'),
('tranny', 'hate speech'),
('hermaphrodite', 'hate speech'),
('bitch', 'hate speech'),
('cunt', 'hate speech'),
('whore', 'hate speech'),
('slut', 'hate speech'),
('skank', 'hate speech'),
('ho', 'hate speech'),
('harlot', 'hate speech'),
('tramp', 'hate speech'),
('slattern', 'hate speech'),
('chhakka', 'hate speech'),
('tranny', 'hate speech'),
('shemale', 'hate speech'),
('ladyboy', 'hate speech'),
('he-she', 'hate speech'),
('kafir', 'hate speech'),
('mulla', 'hate speech'),
('tranny', 'hate speech'),
('kinnar', 'hate speech'),
('freak', 'hate speech'),
('schizo', 'hate speech'),
('insane', 'hate speech'),
('lunatic', 'hate speech'),
('dipshit', 'hate speech'),
('loony', 'hate speech'),
('imbecile', 'hate speech'),
('kill yourself', 'hate speech'),
('you should die', 'hate speech'),
('I hope you get cancer', 'hate speech'),
('you''re worthless', 'hate speech'),
('you''re a failure', 'hate speech'),
('nobody likes you', 'hate speech'),
('you should just disappear', 'hate speech'),
('you''re a waste of space', 'hate speech'),
('everyone hates you', 'hate speech'),
('why are you even alive?', 'hate speech'),
('I wish you were never born', 'hate speech'),
('you''re disgusting', 'hate speech'),
('you''re pathetic', 'hate speech'),
('you make me sick', 'hate speech'),
('you''re a joke', 'hate speech'),
('muslim terrorist', 'hate speech'),
('sikh pujari', 'hate speech'),
('tatti', 'hate speech'),
('Har kudi ko sirf ghar ka kaam karna chahiye, kaam karne kaunsi unki aukat hai?', 'hate_speech'),
('Sardaron ko yahan nahi rehna chahiye, yeh log toh bas apne gaon mein ghoomna chahiye.', 'hate_speech'),
('Hinduon ke desh mein Musalmanon ko nahi rehna chahiye, yeh log toh hamari sanskriti ko bigad rahe hain.', 'hate_speech'),
('LGBTQ logon ko toh chhod do, inka toh koi ilaaj bhi nahi hai. Yeh sab log galat hai aur unhein humare samaj mein jagah nahi honi chahiye.', 'hate_speech'),
('Purushon ko toh mardon ki tarah kaam karna chahiye, aurton ki tarah nahi. Yeh log samaj ko bigad rahe hain.', 'hate_speech'),
('Madraasiyon ko yahan nahi rehna chahiye, inka toh accent bhi sun ne layak nahi hai.', 'hate_speech'),
('Kinner log toh bhagwaan ki galti hain, inhein toh jail mein band kar dena chahiye.', 'hate_speech'),
('Muslim auraton ko toh chhod do, inhein toh sirf bachche paida karne ke liye rakkha gaya hai.', 'hate_speech'),
('Gays aur lesbians toh sirf samaj ko bigad rahe hain, inhein humein sahi disha mein rakhna chahiye.', 'hate_speech'),
('Yeh sab Chinki log humare desh mein kyun rehte hain? Inhein toh wapas bhejna chahiye.', 'hate_speech'),
('Dalit logon ko toh koi adhikaar nahi hai, yeh log sirf gande kaam karna jaante hain.', 'hate_speech'),
('Great job!', 'no_hate_speech'),
('Thank you!', 'no_hate_speech'),
('Well done!', 'no_hate_speech'),
('Awesome!', 'no_hate_speech'),
('Nice work!', 'no_hate_speech'),
('Good job!', 'no_hate_speech'),
('You rock!', 'no_hate_speech'),
('Bravo!', 'no_hate_speech'),
('Fantastic!', 'no_hate_speech'),
('Impressive!', 'no_hate_speech'),
('Keep it up!', 'no_hate_speech'),
('Well said!', 'no_hate_speech'),
('Amazing!', 'no_hate_speech'),
('Superb!', 'no_hate_speech'),
('Excellent!', 'no_hate_speech'),
('Outstanding!', 'no_hate_speech'),
('Terrific!', 'no_hate_speech'),
('You are awesome!', 'no_hate_speech'),
('You are the best!', 'no_hate_speech'),
('You are amazing!', 'no_hate_speech'),
('You are fantastic!', 'no_hate_speech'),
('You are superb!', 'no_hate_speech'),
('You are excellent!', 'no_hate_speech'),
('You are outstanding!', 'no_hate_speech'),
('You are terrific!', 'no_hate_speech');

-- Display the inserted data
SELECT * FROM ChatScreenshots;

